spring.application.name=majorapplication

#server.address=192.168.1.14
#server.address=192.168.55.104

spring.datasource.url=jdbc:postgresql://localhost:5432/majorapplicationbackend
spring.datasource.username=majorapplicationuser
spring.datasource.password=majorapplication@123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



